version: "3.9"

services:
  app:
    build: .
    command: gunicorn -c gunicorn.conf.py app.main:app
    ports:
      - "8000:8000"
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  certbot:
    image: certbot/dns-cloudflare:latest # Или другой DNS провайдер
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot \
             --email your_email@example.com  --agree-tos --no-eff-email \
             -d yourdomain.com -d www.yourdomain.com \
             --deploy-hook "docker-compose exec nginx nginx -s reload"
